# DATASET

In [0]:
import os
os.environ['CUDA_LAUNCH_BLOCKING'] = "1"

In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
!wget -c https://raw.githubusercontent.com/udacity/aind2-nlp-capstone/master/data/small_vocab_en

--2019-05-01 19:02:13--  https://raw.githubusercontent.com/udacity/aind2-nlp-capstone/master/data/small_vocab_en
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9085267 (8.7M) [text/plain]
Saving to: ‘small_vocab_en’

small_vocab_en      100%[===================>]   8.66M  --.-KB/s    in 0.1s    

2019-05-01 19:02:13 (85.1 MB/s) - ‘small_vocab_en’ saved [9085267/9085267]



In [0]:
!wget -c https://raw.githubusercontent.com/udacity/aind2-nlp-capstone/master/data/small_vocab_fr

--2019-05-01 19:02:15--  https://raw.githubusercontent.com/udacity/aind2-nlp-capstone/master/data/small_vocab_fr
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10135742 (9.7M) [text/plain]
Saving to: ‘small_vocab_fr’

small_vocab_fr      100%[===================>]   9.67M  --.-KB/s    in 0.1s    

2019-05-01 19:02:15 (88.2 MB/s) - ‘small_vocab_fr’ saved [10135742/10135742]



In [0]:
  
import os


def load_data(path):
    """
    Load dataset
    """
    input_file = os.path.join(path)
    with open(input_file, "r") as f:
        data = f.read()

    return data.split('\n')

In [0]:

# Load English data
english_sentences = load_data('small_vocab_en')
# Load French data
french_sentences = load_data('small_vocab_fr')

print('Dataset Loaded')

Dataset Loaded


In [0]:
english_sentences[:2]

['new jersey is sometimes quiet during autumn , and it is snowy in april .',
 'the united states is usually chilly during july , and it is usually freezing in november .']

In [0]:
french_sentences[:2]

["new jersey est parfois calme pendant l' automne , et il est neigeux en avril .",
 'les états-unis est généralement froid en juillet , et il gèle habituellement en novembre .']

In [0]:
for sample_i in range(5):
    print('English sample {}:  {}'.format(sample_i + 1, english_sentences[sample_i]))
    print('French sample {}:  {}\n'.format(sample_i + 1, french_sentences[sample_i]))

English sample 1:  new jersey is sometimes quiet during autumn , and it is snowy in april .
French sample 1:  new jersey est parfois calme pendant l' automne , et il est neigeux en avril .

English sample 2:  the united states is usually chilly during july , and it is usually freezing in november .
French sample 2:  les états-unis est généralement froid en juillet , et il gèle habituellement en novembre .

English sample 3:  california is usually quiet during march , and it is usually hot in june .
French sample 3:  california est généralement calme en mars , et il est généralement chaud en juin .

English sample 4:  the united states is sometimes mild during june , and it is cold in september .
French sample 4:  les états-unis est parfois légère en juin , et il fait froid en septembre .

English sample 5:  your least liked fruit is the grape , but my least liked is the apple .
French sample 5:  votre moins aimé fruit est le raisin , mais mon moins aimé est la pomme .



In [0]:
import torch

# Check for a GPU
train_on_gpu = torch.cuda.is_available()
if not train_on_gpu:
    print('No GPU found. Please use a GPU to train your neural network.')

# Preprocess

## Removing Outliers

In [0]:
from collections import Counter
# outlier sentences stats
english_sentences_lens = Counter([len(x) for x in english_sentences])
print("Zero-length english_sentences: {}".format(english_sentences_lens[0]))
print("Maximum english_sentence length: {}".format(max(english_sentences_lens)))

Zero-length english_sentences: 1
Maximum english_sentence length: 102


In [0]:
# outlier sentences stats
french_sentences_lens = Counter([len(x) for x in french_sentences])
print("Zero-length french_sentences: {}".format(french_sentences_lens[0]))
print("Maximum french_sentence length: {}".format(max(french_sentences_lens)))

Zero-length french_sentences: 1
Maximum french_sentence length: 114


In [0]:
print('Number of english_sentences before removing outliers: ', len(english_sentences))
print('Number of frenchh_sentences before removing outliers: ', len(french_sentences))
## remove any reviews/labels with zero length from the reviews_ints list.

# get indices of any reviews with length 0
#non_zero_idx = [ii for ii, sentence in enumerate(english_sentences) if len( sentence) == 0]
english_zero_idx = [ii for ii, sentence in enumerate(english_sentences) if len(sentence) == 0]
french_zero_idx = [ii for ii, sentence in enumerate(french_sentences) if len(sentence) == 0]

print("idx of english_sentence with zero legnth {}".format(english_zero_idx))
print("idx of french_sentence with zero legnth {}".format(french_zero_idx))

Number of english_sentences before removing outliers:  137861
Number of frenchh_sentences before removing outliers:  137861
idx of english_sentence with zero legnth [137860]
idx of french_sentence with zero legnth [137860]


In [0]:
english_sentences[-3:]

['france is never chilly during january , but it is never mild in october .',
 'the orange is her favorite fruit , but the banana is your favorite .',
 '']

In [0]:
french_sentences[-3:]

['la france est jamais froid en janvier , mais il est jamais doux en octobre .',
 "l'orange est son fruit préféré , mais la banane est votre favori .",
 '']

In [0]:
english_sentences.pop(english_zero_idx[0])
french_sentences.pop(french_zero_idx[0])
print('Number of english_sentences after removing outliers: ', len(english_sentences))
print('Number of frenchh_sentences after removing outliers: ', len(french_sentences))

Number of english_sentences after removing outliers:  137860
Number of frenchh_sentences after removing outliers:  137860


## 1 - Tokenize

Tokenize the words into ids

In [0]:
def delimit_sentence(w):
    w = '<sos>' + ' ' + w + ' '+ '<eos>'
    return w

In [0]:
for ii, sentence in enumerate(english_sentences):
    english_sentences[ii] = delimit_sentence(sentence)

In [0]:
english_sentences[:2]

['<sos> new jersey is sometimes quiet during autumn , and it is snowy in april . <eos>',
 '<sos> the united states is usually chilly during july , and it is usually freezing in november . <eos>']

In [0]:
for ii, sentence in enumerate(french_sentences):
    french_sentences[ii] = delimit_sentence(sentence)

In [0]:
french_sentences[:2]

["<sos> new jersey est parfois calme pendant l' automne , et il est neigeux en avril . <eos>",
 '<sos> les états-unis est généralement froid en juillet , et il gèle habituellement en novembre . <eos>']

In [0]:
from string import punctuation

def Tokenizer(sentences):
  
  words = []
  for sentence in sentences:
    for word in sentence.split():
      if word not in punctuation:
        words.append(word)

  return words

In [0]:
from collections import Counter
def create_lookup_tables(text):
    """
    Create lookup tables for vocabulary
    :param text: The text of tv scripts split into words
    :return: A tuple of dicts (vocab_to_int, int_to_vocab)
    """
    # TODO: Implement Function
    words_count = Counter(text) 
    sorted_vocab = sorted(words_count, key=words_count.get, reverse=True)
    
    #vocab_to_int = {word: ii for ii, word in enumerate(sorted_vocab, 1)}
    
    int_to_vocab = {ii: word for ii, word in enumerate(sorted_vocab,1)}
    int_to_vocab[0] = '<pad>'
    vocab_to_int = {word: ii for ii, word in int_to_vocab.items()}
    
    # return tuple
    return vocab_to_int, int_to_vocab

In [0]:
def Tokenize(text):
  
  words = Tokenizer(text)
  vocab_to_int, int_to_vocab = create_lookup_tables(words)
  
  sentences_ints = []
  for sentence in text:
    sentences_ints.append([vocab_to_int[word] for word in sentence.split() if word not in punctuation])
  
  return sentences_ints, vocab_to_int, int_to_vocab

In [0]:
english_sentences_ints, english_vocab_to_int, english_int_to_vocab = Tokenize(english_sentences)
french_sentences_ints, french_vocab_to_int, french_int_to_vocab = Tokenize(french_sentences)

In [0]:
english_sentences_ints[:2]

[[2, 19, 25, 1, 10, 69, 6, 41, 9, 5, 1, 57, 4, 46, 3],
 [2, 7, 22, 23, 1, 11, 64, 6, 45, 9, 5, 1, 11, 53, 4, 47, 3]]

## 2-  Padding

 Add padding to make all the sequences the same length.

In [0]:
import numpy as np
def pad(vocab_ints, seq_length=None):
 
    if (seq_length==None):
        max_len = 0 
        for x in vocab_ints:
          if len(x) > max_len:
            max_len = len(x)
        seq_length = max_len
        
    # getting the correct rows x cols shape
    features = np.zeros((len(vocab_ints), seq_length), dtype=int)

    
    for i, row in enumerate(vocab_ints):
      trunc = row[:seq_length]
      features[i, :len(trunc)] = trunc
    
    return features

In [0]:
english_features = pad(english_sentences_ints)
english_features[0]

array([ 2, 19, 25,  1, 10, 69,  6, 41,  9,  5,  1, 57,  4, 46,  3,  0,  0])

In [0]:
french_features = pad(french_sentences_ints)
french_features[0]

array([  2,  36,  35,   1,  10,  68,  38,  13,  26,   8,   5,   1, 113,
         4,  51,   3,   0,   0,   0,   0,   0,   0,   0])

In [0]:
import numpy as np
english_seq_length = 15

english_features = pad(english_sentences_ints, seq_length=english_seq_length)
english_features[0]

array([ 2, 19, 25,  1, 10, 69,  6, 41,  9,  5,  1, 57,  4, 46,  3])

In [0]:
french_seq_length = 21

french_features = pad(french_sentences_ints, seq_length = french_seq_length)
french_features[0]

array([  2,  36,  35,   1,  10,  68,  38,  13,  26,   8,   5,   1, 113,
         4,  51,   3,   0,   0,   0,   0,   0])

## Preprocess Pipeline


In [0]:
def preprocess(x, y):
    """
    Preprocess x and y
    :param x: Feature List of sentences
    :param y: Label List of sentences
    :return: Tuple of (Preprocessed x, Preprocessed y, x tokenizer, y tokenizer)
    """
    preprocess_x, x_tk, x_tk_rev = Tokenize(x)
    preprocess_y, y_tk, y_tk_rev = Tokenize(y)

    preprocess_x = pad(preprocess_x,23)
    preprocess_y = pad(preprocess_y,23)

    # Keras's sparse_categorical_crossentropy function requires the labels to be in 3 dimensions
    #preprocess_y = preprocess_y.reshape(*preprocess_y.shape, 1)

    return preprocess_x, preprocess_y, x_tk, y_tk, x_tk_rev, y_tk_rev

In [0]:
english_features, french_features, english_tokenizer, french_tokenizer, english_tokenizer_rev, french_tokenizer_rev = preprocess(english_sentences, french_sentences)


In [0]:
french_features.shape

(137860, 23)

In [0]:
english_features.shape

(137860, 23)

## Prep_Orig

In [0]:
# Tokenize Example output
text_sentences = [
    'The quick brown fox jumps over the lazy dog .',
    'By Jove , my quick study of lexicography won a prize .',
    'This is a short sentence .']
text_tokenized, text_tokenizer, text_tokenizer_rev = Tokenize(text_sentences)
print(text_tokenized)
print()
for sample_i, (sent, token_sent) in enumerate(zip(text_sentences, text_tokenized)):
    print('Sequence {} in x'.format(sample_i + 1))
    print('  Input:  {}'.format(sent))
    print('  Output: {}'.format(token_sent))

[[3, 1, 4, 5, 6, 7, 8, 9, 10], [11, 12, 13, 1, 14, 15, 16, 17, 2, 18], [19, 20, 2, 21, 22]]

Sequence 1 in x
  Input:  The quick brown fox jumps over the lazy dog .
  Output: [3, 1, 4, 5, 6, 7, 8, 9, 10]
Sequence 2 in x
  Input:  By Jove , my quick study of lexicography won a prize .
  Output: [11, 12, 13, 1, 14, 15, 16, 17, 2, 18]
Sequence 3 in x
  Input:  This is a short sentence .
  Output: [19, 20, 2, 21, 22]


In [0]:
# Pad Tokenized output
test_pad = pad(text_tokenized)
for sample_i, (token_sent, pad_sent) in enumerate(zip(text_tokenized, test_pad)):
    print('Sequence {} in x'.format(sample_i + 1))
    print('  Input:  {}'.format(np.array(token_sent)))
    print('  Output: {}'.format(pad_sent))

Sequence 1 in x
  Input:  [ 3  1  4  5  6  7  8  9 10]
  Output: [ 3  1  4  5  6  7  8  9 10  0]
Sequence 2 in x
  Input:  [11 12 13  1 14 15 16 17  2 18]
  Output: [11 12 13  1 14 15 16 17  2 18]
Sequence 3 in x
  Input:  [19 20  2 21 22]
  Output: [19 20  2 21 22  0  0  0  0  0]


In [0]:
for sample_i in range(5):
    print('small_vocab_en Line {}:  {}'.format(sample_i + 1, english_sentences[sample_i]))
    print('small_vocab_fr Line {}:  {}'.format(sample_i + 1, french_sentences[sample_i]))

small_vocab_en Line 1:  <sos> new jersey is sometimes quiet during autumn , and it is snowy in april . <eos>
small_vocab_fr Line 1:  <sos> new jersey est parfois calme pendant l' automne , et il est neigeux en avril . <eos>
small_vocab_en Line 2:  <sos> the united states is usually chilly during july , and it is usually freezing in november . <eos>
small_vocab_fr Line 2:  <sos> les états-unis est généralement froid en juillet , et il gèle habituellement en novembre . <eos>
small_vocab_en Line 3:  <sos> california is usually quiet during march , and it is usually hot in june . <eos>
small_vocab_fr Line 3:  <sos> california est généralement calme en mars , et il est généralement chaud en juin . <eos>
small_vocab_en Line 4:  <sos> the united states is sometimes mild during june , and it is cold in september . <eos>
small_vocab_fr Line 4:  <sos> les états-unis est parfois légère en juin , et il fait froid en septembre . <eos>
small_vocab_en Line 5:  <sos> your least liked fruit is the grap

In [0]:
from collections import Counter

english_words_counter = Counter([word for sentence in english_sentences for word in sentence.split()])
french_words_counter = Counter([word for sentence in french_sentences for word in sentence.split()])

print('{} English words.'.format(len([word for sentence in english_sentences for word in sentence.split()])))
print('{} unique English words.'.format(len(english_words_counter)))
print('10 Most common words in the English dataset:')
print('"' + '" "'.join(list(zip(*english_words_counter.most_common(10)))[0]) + '"')
print()
print('{} French words.'.format(len([word for sentence in french_sentences for word in sentence.split()])))
print('{} unique French words.'.format(len(french_words_counter)))
print('10 Most common words in the French dataset:')
print('"' + '" "'.join(list(zip(*french_words_counter.most_common(10)))[0]) + '"')

2098970 English words.
229 unique English words.
10 Most common words in the English dataset:
"is" "," "<sos>" "<eos>" "." "in" "it" "during" "the" "but"

2237015 French words.
357 unique French words.
10 Most common words in the French dataset:
"est" "<sos>" "<eos>" "." "," "en" "il" "les" "mais" "et"


In [0]:
preproc_english_sentences, preproc_french_sentences, english_tokenizer, french_tokenizer, english_tokenizer_rev, french_tokenizer_rev =\
    preprocess(english_sentences, french_sentences)
    
max_english_sequence_length = preproc_english_sentences.shape[1]
max_french_sequence_length = preproc_french_sentences.shape[1]
english_vocab_size = len(english_tokenizer)
french_vocab_size = len(french_tokenizer)

print('Data Preprocessed')
print("Max English sentence length:", max_english_sequence_length)
print("Max French sentence length:", max_french_sequence_length)
print("English vocabulary size:", english_vocab_size)
print("French vocabulary size:", french_vocab_size)

Data Preprocessed
Max English sentence length: 23
Max French sentence length: 23
English vocabulary size: 227
French vocabulary size: 354


## Training, Validation, Test

In [0]:
split_frac = 0.8

## split data into training, validation, and test data (features and labels, x and y)


split_idx = int(len(english_features)*split_frac)
train_x, remaining_x = english_features[:split_idx], english_features[split_idx:]
train_y, remaining_y = french_features[:split_idx], french_features[split_idx:]

test_idx = int(len(remaining_x)*0.5)
val_x, test_x = remaining_x[:test_idx], remaining_x[test_idx:]
val_y, test_y = remaining_y[:test_idx], remaining_y[test_idx:]

## print out the shapes of your resultant feature data
print("\t\t\tFeature Shapes:")
print("Train set: \t\t{}".format(train_x.shape), 
      "\nValidation set: \t{}".format(val_x.shape),
      "\nTest set: \t\t{}".format(test_x.shape))

## print out the shapes of your resultant feature data
print("\t\t\tTarget Shapes:")
print("Train Targets: \t\t{}".format(train_y.shape), 
      "\nValidation Targets: \t{}".format(val_y.shape),
      "\nTest Targets: \t\t{}".format(test_y.shape))

			Feature Shapes:
Train set: 		(110288, 23) 
Validation set: 	(13786, 23) 
Test set: 		(13786, 23)
			Target Shapes:
Train Targets: 		(110288, 23) 
Validation Targets: 	(13786, 23) 
Test Targets: 		(13786, 23)


## DataLoaders and Batching


In [0]:
import torch
from torch.utils.data import TensorDataset, DataLoader

# create Tensor datasets
train_data = TensorDataset(torch.from_numpy(train_x), torch.from_numpy(train_y))
valid_data = TensorDataset(torch.from_numpy(val_x), torch.from_numpy(val_y))
test_data = TensorDataset(torch.from_numpy(test_x), torch.from_numpy(test_y))

# dataloaders
batch_size = 64

# make sure the SHUFFLE your training data
#train_loader = DataLoader(train_data, shuffle=True, batch_size=batch_size)
#valid_loader = DataLoader(valid_data, shuffle=True, batch_size=batch_size)
#test_loader = DataLoader(test_data, shuffle=True, batch_size=batch_size)

In [0]:
dataloaders = {
    'train': DataLoader(train_data, shuffle=True, batch_size=batch_size),
    'valid': DataLoader(valid_data, shuffle=True, batch_size=batch_size),
    'test': DataLoader(test_data, shuffle=True, batch_size=batch_size)
}


device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu") 


In [0]:

dataset_sizes = {
    'train': len(train_data),
    'valid': len(valid_data),
    'test': len(test_data),
}
                
print(dataset_sizes['train'])
print(dataset_sizes['valid'])
print(dataset_sizes['test'])

110288
13786
13786


In [0]:
# obtain one batch of training data
dataiter = iter(dataloaders['train'])
sample_x, sample_y = dataiter.next()

print('Sample input size: ', sample_x.size()) # batch_size, seq_length
print('Sample input: \n', sample_x)
print()
print('Sample label size: ', sample_y.size()) # batch_size
print('Sample label: \n', sample_y)

Sample input size:  torch.Size([64, 23])
Sample input: 
 tensor([[ 2, 24,  1,  ...,  0,  0,  0],
        [ 2, 21,  1,  ...,  0,  0,  0],
        [ 2, 19, 25,  ...,  0,  0,  0],
        ...,
        [ 2, 52, 13,  ...,  0,  0,  0],
        [ 2, 27,  1,  ...,  0,  0,  0],
        [ 2, 51, 13,  ...,  0,  0,  0]])

Sample label size:  torch.Size([64, 23])
Sample label: 
 tensor([[  2, 102,   1,  ...,   0,   0,   0],
        [  2,  13,  32,  ...,   0,   0,   0],
        [  2,  36,  35,  ...,   0,   0,   0],
        ...,
        [  2,  65,  18,  ...,   0,   0,   0],
        [  2,  37,   1,  ...,   0,   0,   0],
        [  2,  62,  18,  ...,   0,   0,   0]])


In [0]:
x = sample_x.transpose(0, 1)
y = sample_y.transpose(0, 1)

print('Sample input size: ', x.size()) # batch_size, seq_length
print('Sample input: \n', x)
print()
print('Sample label size: ', y.size()) # batch_size
print('Sample label: \n', y)

Sample input size:  torch.Size([23, 64])
Sample input: 
 tensor([[ 2,  2,  2,  ...,  2,  2,  2],
        [24, 21, 19,  ..., 52, 27, 51],
        [ 1,  1, 25,  ..., 13,  1, 13],
        ...,
        [ 0,  0,  0,  ...,  0,  0,  0],
        [ 0,  0,  0,  ...,  0,  0,  0],
        [ 0,  0,  0,  ...,  0,  0,  0]])

Sample label size:  torch.Size([23, 64])
Sample label: 
 tensor([[  2,   2,   2,  ...,   2,   2,   2],
        [102,  13,  36,  ...,  65,  37,  62],
        [  1,  32,  35,  ...,  18,   1,  18],
        ...,
        [  0,   0,   0,  ...,   0,   0,   0],
        [  0,   0,   0,  ...,   0,   0,   0],
        [  0,   0,   0,  ...,   0,   0,   0]])


In [0]:
sample_x0 = sample_x[-1].cpu().detach().numpy()

' '.join([english_tokenizer_rev[x] for x in sample_x0])

'<sos> our least favorite fruit is the peach but their least favorite is the strawberry <eos> <pad> <pad> <pad> <pad> <pad> <pad> <pad>'

In [0]:
sample_y[-1]

tensor([  2,  62,  18,  19,  15,   1,   9,  91,   7,  65,  15, 142,   1,   9,
         90,   3,   0,   0,   0,   0,   0,   0,   0])

In [0]:
sample_y0 = sample_y[-1].cpu().detach().numpy()

' '.join([french_tokenizer_rev[x] for x in sample_y0])

'<sos> notre fruit préféré moins est la pêche mais leur moins préférée est la fraise <eos> <pad> <pad> <pad> <pad> <pad> <pad> <pad>'

In [0]:
def logits_to_text(logits, tokenizer):
    """
    Turn logits from a neural network into text using the tokenizer
    :param logits: Logits from a neural network
    :param tokenizer: Keras Tokenizer fit on the labels
    :return: String that represents the text of the logits
    """
    

    return ' '.join([tokenizer[prediction] for prediction in np.argmax(logits, 1)])

print('`logits_to_text` function loaded.')

`logits_to_text` function loaded.


# Model

In [0]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [0]:
import math
import torch
import random
from torch import nn
from torch.autograd import Variable
import torch.nn.functional as F


class Encoder(nn.Module):
    def __init__(self, input_size, embed_size, hidden_size,
                 n_layers=1, dropout=0.5):
        super(Encoder, self).__init__()
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.embed_size = embed_size
        self.embed = nn.Embedding(input_size, embed_size)
        self.gru = nn.GRU(embed_size, hidden_size, n_layers,
                          dropout=dropout, bidirectional=True)

    def forward(self, src, hidden=None):
        embedded = self.embed(src)
        outputs, hidden = self.gru(embedded, hidden)
        # sum bidirectional outputs
        outputs = (outputs[:, :, :self.hidden_size] +
                   outputs[:, :, self.hidden_size:])
        return outputs, hidden


class Attention(nn.Module):
    def __init__(self, hidden_size):
        super(Attention, self).__init__()
        self.hidden_size = hidden_size
        self.attn = nn.Linear(self.hidden_size * 2, hidden_size)
        self.v = nn.Parameter(torch.rand(hidden_size))
        stdv = 1. / math.sqrt(self.v.size(0))
        self.v.data.uniform_(-stdv, stdv)

    def forward(self, hidden, encoder_outputs):
        timestep = encoder_outputs.size(0)
        h = hidden.repeat(timestep, 1, 1).transpose(0, 1)
        encoder_outputs = encoder_outputs.transpose(0, 1)  # [B*T*H]
        attn_energies = self.score(h, encoder_outputs)
        return F.relu(attn_energies).unsqueeze(1)

    def score(self, hidden, encoder_outputs):
        # [B*T*2H]->[B*T*H]
        energy = F.softmax(self.attn(torch.cat([hidden, encoder_outputs], 2)), dim=2)
        
        energy = energy.transpose(1, 2)  # [B*H*T]
        v = self.v.repeat(encoder_outputs.size(0), 1).unsqueeze(1)  # [B*1*H]
        energy = torch.bmm(v, energy)  # [B*1*T]
        return energy.squeeze(1)  # [B*T]


class Decoder(nn.Module):
    def __init__(self, embed_size, hidden_size, output_size,
                 n_layers=1, dropout=0.2):
        super(Decoder, self).__init__()
        self.embed_size = embed_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        self.n_layers = n_layers

        self.embed = nn.Embedding(output_size, embed_size)
        self.dropout = nn.Dropout(dropout, inplace=True)
        self.attention = Attention(hidden_size)
        self.gru = nn.GRU(hidden_size + embed_size, hidden_size,
                          n_layers, dropout=dropout)
        self.out = nn.Linear(hidden_size * 2, output_size)

    def forward(self, input, last_hidden, encoder_outputs):
        # Get the embedding of the current input word (last output word)
        embedded = self.embed(input).unsqueeze(0)  # (1,B,N)
        embedded = self.dropout(embedded)
        # Calculate attention weights and apply to encoder outputs
        attn_weights = self.attention(last_hidden[-1], encoder_outputs)
        context = attn_weights.bmm(encoder_outputs.transpose(0, 1))  # (B,1,N)
        context = context.transpose(0, 1)  # (1,B,N)
        #print(context.size())
        #print(embedded.size())
        embedded = embedded.squeeze(2)
        #print(embedded.size())
        # Combine embedded input word and attended context, run through RNN
        rnn_input = torch.cat([embedded, context], 2)
        output, hidden = self.gru(rnn_input, last_hidden)
        output = output.squeeze(0)  # (1,B,N) -> (B,N)
        context = context.squeeze(0)
        output = self.out(torch.cat([output, context], 1))
        output = F.log_softmax(output, dim=1)
        return output, hidden, attn_weights


class Seq2Seq(nn.Module):
    def __init__(self, encoder, decoder):
        super(Seq2Seq, self).__init__()
        self.encoder = encoder
        self.decoder = decoder

    def forward(self, src, trg, teacher_forcing_ratio=0.5):
        batch_size = src.size(1)
        max_len = src.size(0)
        vocab_size = self.decoder.output_size
        outputs = Variable(torch.zeros(max_len, batch_size, vocab_size)).cuda()
        preds = Variable(torch.zeros(max_len, batch_size)).cuda()
        
        encoder_output, hidden = self.encoder(src)
        hidden = hidden[:self.decoder.n_layers]
        output = Variable(trg.data[0, :])  # sos
        for t in range(1, max_len):
            output, hidden, attn_weights = self.decoder(
                    output, hidden, encoder_output)
            outputs[t] = output
            is_teacher = random.random() < teacher_forcing_ratio
            top1 = output.data.max(1)[1]
            preds[t] = top1 
            output = Variable(trg.data[t] if is_teacher else top1).cuda()
        #print("output" )
        #print(output.size())    
        #print("outputs") 
        #print(outputs.size())
        #print("top1")
        #print(top1.size())
        #print("preds")
        #print( preds.size())
        return outputs, preds

In [0]:
### Testing Encoder part
# TODO: put whether GPU is available or not
# Device
en_size, fr_size = len(english_tokenizer), len(french_tokenizer)
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
encoder = Encoder(input_size = en_size, embed_size= 256, hidden_size = 512, n_layers=1, dropout=0.5)

encoder.to(device)
# obtain one sample from the data iterator
it = iter(dataloaders['train'])
x, y = next(it)

# sort the batch first to be able to use with pac_pack_sequence
xs = x.transpose(0, 1)
ys = y.transpose(0, 1)

enc_output, enc_hidden = encoder(xs.to(device))
print(enc_output.size()) # max_length, batch_size, enc_units

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/rnn.py:46: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.5 and num_layers=1
  "num_layers={}".format(dropout, num_layers))


torch.Size([23, 64, 512])


In [0]:
# Device
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
encoder = Encoder(input_size = en_size, embed_size= 256, hidden_size = 512, n_layers=1, dropout=0.5)

encoder.to(device)
# obtain one sample from the data iterator
it = iter(dataloaders['train'])
x, y = next(it)

print("Input: ", x.shape)
print("Output: ", y.shape)

# sort the batch first to be able to use with pac_pack_sequence
xs = x.transpose(0, 1)
ys = y.transpose(0, 1)
enc_output, enc_hidden = encoder(xs.to(device))

print("Encoder Output: ", enc_output.shape) # batch_size X max_length X enc_units
print("Encoder Hidden: ", enc_hidden.shape) # batch_size X enc_units (corresponds to the last state)

decoder = Decoder(embed_size= 256, hidden_size = 512, output_size = fr_size, n_layers=1, dropout=0.2)
decoder = decoder.to(device)

#print(enc_hidden.squeeze(0).shape)

dec_hidden = enc_hidden[:1]#.squeeze(0)
dec_input = torch.tensor([[french_tokenizer['<sos>']]] * 64)
print("Decoder Input: ", dec_input.shape)
print("--------")

for t in range(1, y.size(1)):
    # enc_hidden: 1, batch_size, enc_units
    # output: max_length, batch_size, enc_units
    
    predictions, dec_hidden, attn_weights = decoder(dec_input.to(device), 
                                         dec_hidden.to(device), 
                                         enc_output.to(device))
    
    print("Prediction: ", predictions.shape)
    print("Decoder Hidden: ", dec_hidden.shape)
    
    #loss += loss_function(y[:, t].to(device), predictions.to(device))
    
    dec_input = y[:, t].unsqueeze(1)
    print(dec_input.shape)
    break

Input:  torch.Size([64, 23])
Output:  torch.Size([64, 23])
Encoder Output:  torch.Size([23, 64, 512])
Encoder Hidden:  torch.Size([2, 64, 512])
Decoder Input:  torch.Size([64, 1])
--------
Prediction:  torch.Size([64, 354])
Decoder Hidden:  torch.Size([1, 64, 512])
torch.Size([64, 1])


/usr/local/lib/python3.6/dist-packages/torch/nn/modules/rnn.py:46: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.5 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/rnn.py:46: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.2 and num_layers=1
  "num_layers={}".format(dropout, num_layers))


In [0]:
# Device
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
encoder = Encoder(input_size = en_size, embed_size= 256, hidden_size = 512, n_layers=1, dropout=0.5)

encoder.to(device)
# obtain one sample from the data iterator
it = iter(dataloaders['train'])
x, y = next(it)

print("Input: ", x.shape)
print("Output: ", y.shape)

# sort the batch first to be able to use with pac_pack_sequence
xs = x.transpose(0, 1)
ys = y.transpose(0, 1)
enc_output, enc_hidden = encoder(xs.to(device))

print("Encoder Output: ", enc_output.shape) # batch_size X max_length X enc_units
print("Encoder Hidden: ", enc_hidden.shape) # batch_size X enc_units (corresponds to the last state)

decoder = Decoder(embed_size= 256, hidden_size = 512, output_size = fr_size, n_layers=1, dropout=0.2)
decoder = decoder.to(device)

#print(enc_hidden.squeeze(0).shape)

seq2seq = Seq2Seq(encoder, decoder).to(device)

outputs, preds = seq2seq(xs.to(device),ys.to(device))
print("seq2seq Outputs: ", outputs.shape) # batch_size X max_length X enc_units
print("seq2seq predictions: ", preds.shape) # batch_size X enc_units (corresponds to the last state)
print("seq2seq targets: ", ys.shape)
print (ys)
print (preds)

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/rnn.py:46: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.5 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/rnn.py:46: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.2 and num_layers=1
  "num_layers={}".format(dropout, num_layers))


Input:  torch.Size([64, 23])
Output:  torch.Size([64, 23])
Encoder Output:  torch.Size([23, 64, 512])
Encoder Hidden:  torch.Size([2, 64, 512])
seq2seq Outputs:  torch.Size([23, 64, 354])
seq2seq predictions:  torch.Size([23, 64])
seq2seq targets:  torch.Size([23, 64])
tensor([[  2,   2,   2,  ...,   2,   2,   2],
        [ 12,  37,  36,  ...,   6,  29,  65],
        [ 39,   1,  35,  ...,  33, 289,  18],
        ...,
        [  0,   0,   0,  ...,   0,   0,   0],
        [  0,   0,   0,  ...,   0,   0,   0],
        [  0,   0,   0,  ...,   0,   0,   0]])
tensor([[  0.,   0.,   0.,  ...,   0.,   0.,   0.],
        [306., 159., 278.,  ..., 159., 191., 159.],
        [ 88.,  33.,  10.,  ..., 159., 326., 228.],
        ...,
        [ 61.,  92., 125.,  ..., 327., 242., 125.],
        [243., 327., 327.,  ..., 327.,  92., 327.],
        [243., 327., 327.,  ..., 327., 327.,  92.]], device='cuda:0')


In [0]:
import os
import math
import argparse
import copy
import time

import torch
from torch import optim
from torch.autograd import Variable
from torch.nn.utils import clip_grad_norm
from torch.nn import functional as F

def train_model(model, model_loss, optimizer, num_epochs, vocab_size, grad_clip, french_tokenizer, english_tokenizer):
    since = time.time()

    best_model_wts = copy.deepcopy(model.state_dict())
    best_model_wts_loss = copy.deepcopy(model.state_dict())
    best_acc = 0.0
    best_loss = 0.0
    best_acc_loss = 0.0
    best_loss_acc = 0.0
   
    valid_acc_history = []
    valid_loss_history = []
    train_acc_history = []
    train_loss_history = []
    
    total_loss = 0
    
    model_save_name = 'checkpoint_seq2seq_train_v0.pth'
    model_save_loss = 'checkpoint_seq2seq_loss_v0.pth'
    path = F"/content/gdrive/My Drive/{model_save_name}" 
    path_loss = F"/content/gdrive/My Drive/{model_save_loss}" 
    
    pad = english_tokenizer['<pad>']
    
    for epoch in range(1, num_epochs+1):
        print('Epoch {}/{}'.format(epoch, num_epochs))
        print('-' * 10)

        # Each epoch has a training and validation phase
        for phase in ['train', 'valid']:
            if phase == 'train':
                #scheduler.step()
                model.train()  # Set model to training mode
            else:
                model.eval()   # Set model to evaluate mode

            running_loss = 0.0
            running_corrects = 0.0
            total = 0
            # Iterate over data.
            for inputs, labels in dataloaders[phase]:
              
                inputs = inputs.transpose(0, 1)
                labels = labels.transpose(0, 1)
                
                inputs = inputs.to(device)
                labels = labels.to(device)

                # zero the parameter gradients
                optimizer.zero_grad()

                # forward
                # track history if only in train
                with torch.set_grad_enabled(phase == 'train'):
                    outputs, preds = model(inputs,labels)
                    #_, preds = torch.max(outputs, 1)
                    loss = F.nll_loss(outputs[1:].view(-1, vocab_size), labels[1:].contiguous().view(-1), ignore_index=pad)
                    
                    
                    # backward + optimize only if in training phase
                    if phase == 'train':
                        loss.backward()
                        clip_grad_norm(model.parameters(), grad_clip)
                        optimizer.step()
                       

                # statistics
                #running_loss += loss.data loss.item() / labels.size(0)
                
                running_loss += loss.data
                
                preds  = preds.float()
                labels  = labels.float()
                non_padding = labels.ne(pad)
                corrects = preds.eq(labels.data).masked_select(non_padding).sum().item()
                running_corrects += corrects
                total += non_padding.sum().item()
                    

            epoch_loss = running_loss / len(dataloaders[phase])
            epoch_acc = (running_corrects / total) * 100
            
             
      
           
            # deep copy the model
            if phase == 'valid' and epoch_acc >= best_acc:
              if epoch_acc > best_acc:
                best_acc = epoch_acc
                best_acc_loss = epoch_loss
                best_model_wts = copy.deepcopy(model.state_dict())
                torch.save(model.state_dict(), path)
              elif epoch_acc == best_acc:
                if epoch_loss < best_acc_loss: 
                  best_acc = epoch_acc
                  best_acc_loss = epoch_loss
                  best_model_wts = copy.deepcopy(model.state_dict())
                  torch.save(model.state_dict(), path)
            if phase == 'valid' and epoch_loss < best_loss:
                best_loss = epoch_loss
                best_loss_acc = epoch_acc
                best_model_wts_loss = copy.deepcopy(model.state_dict())
                torch.save(model.state_dict(), path_loss)
            if phase == 'valid':
                valid_loss_history.append(epoch_loss)
                valid_acc_history.append(epoch_acc)
            if phase == 'train':
                train_loss_history.append(epoch_loss)
                train_acc_history.append(epoch_acc)
                
            print('{} Loss: {:.4f} Acc: {:.4f} Best val Acc: {:4f} Best_val_Acc_Loss: {:4f} Best_val_Loss: {:4f} Best_val_Loss_acc: {:4f} '.format(phase, epoch_loss, epoch_acc, best_acc, best_acc_loss, best_loss, best_loss_acc))
                
            

        print()
        

    time_elapsed = time.time() - since
    print('Training complete in {:.0f}m {:.0f}s'.format(
        time_elapsed // 60, time_elapsed % 60))
    print('Best val Acc: {:4f}'.format(best_acc))
    print('Best val Acc Loss: {:4f}'.format(best_acc_loss))
    print('Best val Loss: {:4f}'.format(best_loss))
    print('Best val Loss Acc: {:4f}'.format(best_loss_acc))
    
    
    
    # load best model weights
    model.load_state_dict(best_model_wts)
    model_loss.load_state_dict(best_model_wts_loss)
    return model, model_loss, train_acc_history, valid_acc_history, train_loss_history, valid_loss_history

In [0]:
    hidden_size = 512
    embed_size = 256
    
    epochs=25
                   
    batch_size=64
    
    lr=0.001
    
    grad_clip=5.0
    
                  
    
    assert torch.cuda.is_available()

    print("[!] preparing dataset...")
     
    en_size, fr_size = len(english_tokenizer), len(french_tokenizer)
    print("[TRAIN]:%d (dataset:%d)\t[TEST]:%d (dataset:%d)"
          % (len(dataloaders['train']), len(dataloaders['train'].dataset),
             len(dataloaders['train']), len(dataloaders['train'].dataset)))
    print("[fr_vocab]:%d [en_vocab]:%d" % (fr_size, en_size))

    print("[!] Instantiating models...")
    encoder = Encoder(en_size, embed_size, hidden_size, n_layers=2, dropout=0.5)
    decoder = Decoder(embed_size, hidden_size, fr_size, n_layers=1, dropout=0.5)
    seq2seq = Seq2Seq(encoder, decoder).to(device)
    seq2seq_loss = Seq2Seq(encoder, decoder).to(device)
    optimizer = optim.Adam(seq2seq.parameters(), lr=lr)
    print(seq2seq)

[!] preparing dataset...
[TRAIN]:1724 (dataset:110288)	[TEST]:1724 (dataset:110288)
[fr_vocab]:354 [en_vocab]:227
[!] Instantiating models...
Seq2Seq(
  (encoder): Encoder(
    (embed): Embedding(227, 256)
    (gru): GRU(256, 512, num_layers=2, dropout=0.5, bidirectional=True)
  )
  (decoder): Decoder(
    (embed): Embedding(354, 256)
    (dropout): Dropout(p=0.5, inplace)
    (attention): Attention(
      (attn): Linear(in_features=1024, out_features=512, bias=True)
    )
    (gru): GRU(768, 512, dropout=0.5)
    (out): Linear(in_features=1024, out_features=354, bias=True)
  )
)


/usr/local/lib/python3.6/dist-packages/torch/nn/modules/rnn.py:46: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.5 and num_layers=1
  "num_layers={}".format(dropout, num_layers))


In [0]:
model_loss = Seq2Seq(encoder, decoder).to(device)

In [0]:
model = Seq2Seq(encoder, decoder).to(device)

In [0]:
model, model_loss, train_hist, valid_hist, train_loss_history, valid_loss_history = train_model(seq2seq, seq2seq_loss, optimizer, epochs+1, fr_size, grad_clip, french_tokenizer, english_tokenizer)

Epoch 1/26
----------


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:75: UserWarning: torch.nn.utils.clip_grad_norm is now deprecated in favor of torch.nn.utils.clip_grad_norm_.


train Loss: 1.0313 Acc: 66.1489 Best val Acc: 0.000000 Best_val_Acc_Loss: 0.000000 Best_val_Loss: 0.000000 Best_val_Loss_acc: 0.000000 
valid Loss: 0.4562 Acc: 80.5563 Best val Acc: 80.556274 Best_val_Acc_Loss: 0.456208 Best_val_Loss: 0.000000 Best_val_Loss_acc: 0.000000 

Epoch 2/26
----------
train Loss: 0.3426 Acc: 82.8409 Best val Acc: 80.556274 Best_val_Acc_Loss: 0.456208 Best_val_Loss: 0.000000 Best_val_Loss_acc: 0.000000 
valid Loss: 0.2488 Acc: 85.3792 Best val Acc: 85.379174 Best_val_Acc_Loss: 0.248849 Best_val_Loss: 0.000000 Best_val_Loss_acc: 0.000000 

Epoch 3/26
----------
train Loss: 0.1795 Acc: 87.7080 Best val Acc: 85.379174 Best_val_Acc_Loss: 0.248849 Best_val_Loss: 0.000000 Best_val_Loss_acc: 0.000000 
valid Loss: 0.1311 Acc: 89.1625 Best val Acc: 89.162547 Best_val_Acc_Loss: 0.131061 Best_val_Loss: 0.000000 Best_val_Loss_acc: 0.000000 

Epoch 4/26
----------
train Loss: 0.1182 Acc: 89.6121 Best val Acc: 89.162547 Best_val_Acc_Loss: 0.131061 Best_val_Loss: 0.000000 Be

In [0]:
model

Seq2Seq(
  (encoder): Encoder(
    (embed): Embedding(227, 256)
    (gru): GRU(256, 512, num_layers=2, dropout=0.5, bidirectional=True)
  )
  (decoder): Decoder(
    (embed): Embedding(354, 256)
    (dropout): Dropout(p=0.5, inplace)
    (attention): Attention(
      (attn): Linear(in_features=1024, out_features=512, bias=True)
    )
    (gru): GRU(768, 512, dropout=0.5)
    (out): Linear(in_features=1024, out_features=354, bias=True)
  )
)

In [0]:
def evaluate_valid(model, vocab_size, french_tokenizer, english_tokenizer):
    model.eval()
    model.to(device)
    accuracy = 0
    test_error = 0
    test_accuracy = 0 
    pad = english_tokenizer['<pad>']
    
    total = 0
    total_loss = 0
    
    for src, trg in dataloaders['valid']:
        src = src.transpose(0, 1)
        trg = trg.transpose(0, 1)
        src = src.to(device)
        trg = trg.to(device)
        with torch.no_grad():
            output, pred = model(src, trg)
         
        loss = F.nll_loss(output[1:].view(-1, vocab_size),trg[1:].contiguous().view(-1), ignore_index=pad)
        total_loss += loss.data
        
       
        pred = pred.float()
        trg  = trg.float()
        non_padding = trg.ne(pad)
        corrects = pred.eq(trg.data).masked_select(non_padding).sum().item()
        accuracy += corrects
        total += non_padding.sum().item()
        #print(accuracy)
        
    test_error = total_loss / len(dataloaders['valid'])
    test_accuracy = ( accuracy / total  ) * 100
    
    
    return test_error, test_accuracy

In [0]:
for name,param in model.named_parameters():
  print(name)
  print(param.data)
  

encoder.embed.weight
tensor([[-1.1652,  0.0564,  1.7151,  ..., -1.1676,  0.8155,  1.0169],
        [ 0.2293,  0.2063,  0.5326,  ...,  1.5195,  1.4301,  1.0686],
        [ 1.5813, -1.3332,  1.2815,  ..., -1.4151,  0.0031, -0.5095],
        ...,
        [ 1.0775,  0.0871, -0.1687,  ..., -1.1340,  0.0905,  1.1670],
        [-0.1030, -0.5513,  0.5572,  ...,  1.3435, -0.7266, -0.0171],
        [ 0.7430,  1.8899, -1.0459,  ..., -0.5868,  0.0818,  0.9288]],
       device='cuda:0')
encoder.gru.weight_ih_l0
tensor([[ 0.0200,  0.0399, -0.0164,  ...,  0.0404, -0.0421,  0.0101],
        [ 0.0426,  0.0325, -0.0166,  ..., -0.0163, -0.0030, -0.0329],
        [ 0.0096,  0.0336,  0.0145,  ...,  0.0098,  0.0014,  0.0284],
        ...,
        [ 0.0395, -0.0059, -0.0254,  ..., -0.0416,  0.0345, -0.0318],
        [-0.0237,  0.0435,  0.0067,  ..., -0.0126, -0.0105, -0.0006],
        [ 0.0227,  0.0251, -0.0289,  ...,  0.0348,  0.0310, -0.0030]],
       device='cuda:0')
encoder.gru.weight_hh_l0
tensor([[ 0.0

In [0]:
model_save_name = 'checkpoint_seq2seq_train_v0.pth'
path = F"/content/gdrive/My Drive/{model_save_name}" 
  

In [0]:
model_save_loss = 'checkpoint_seq2seq_loss_v0.pth'
path_loss = F"/content/gdrive/My Drive/{model_save_loss}" 

In [0]:
model.load_state_dict(torch.load(path))

In [0]:
for name,param in model.named_parameters():
  print(name)
  print(param.data)
  

encoder.embed.weight
tensor([[ 0.3022, -0.1318,  1.9882,  ...,  0.2907, -0.3224,  0.5976],
        [-0.7091, -0.9527,  0.1287,  ..., -0.3062,  0.0296,  0.3808],
        [-0.8138, -0.8229, -0.3540,  ..., -0.5451, -1.4748, -1.4022],
        ...,
        [ 0.3804,  0.9543, -1.3726,  ..., -1.1366,  0.1893,  1.1785],
        [-1.0030, -0.3153,  0.7899,  ...,  0.2195,  0.4086, -2.0941],
        [-0.2088,  0.4728,  1.2621,  ..., -2.0619,  1.5998,  0.2934]],
       device='cuda:0')
encoder.gru.weight_ih_l0
tensor([[ 0.1538, -0.1584,  0.0512,  ...,  0.1356,  0.0815, -0.1827],
        [-0.1486,  0.3912,  0.1574,  ..., -0.0408, -0.0631, -0.2040],
        [-0.0029,  0.0656,  0.3741,  ..., -0.1935,  0.2431, -0.2227],
        ...,
        [ 0.1009,  0.2239,  0.3391,  ...,  0.0924, -0.1031,  0.0724],
        [ 0.2108,  0.0925,  0.0239,  ...,  0.1695, -0.2077, -0.2077],
        [-0.0805,  0.2197, -0.2664,  ..., -0.2263, -0.0938, -0.1104]],
       device='cuda:0')
encoder.gru.weight_hh_l0
tensor([[-0.0

In [0]:
test_loss, test_accuracy = evaluate_valid(model, fr_size, french_tokenizer, english_tokenizer)
print(test_loss)
print(test_accuracy)

tensor(0.0485, device='cuda:0')
91.94797292157907


In [0]:
def evaluate(model, vocab_size, french_tokenizer, english_tokenizer):
    model.eval()
    model.to(device)
    accuracy = 0
    test_error = 0

    pad = english_tokenizer['<pad>']
    
    total = 0
    total_loss = 0
    accuracy = 0
    for src, trg in dataloaders['test']:
        src = src.transpose(0, 1)
        trg = trg.transpose(0, 1)
        src = src.to(device)
        trg = trg.to(device)
        with torch.no_grad():
            output, pred = model(src, trg, teacher_forcing_ratio=0.0)
         
        loss = F.nll_loss(output[1:].view(-1, vocab_size),trg[1:].contiguous().view(-1), ignore_index=pad)
        total_loss += loss.data
        
       
        pred = pred.float()
        trg  = trg.float()
        non_padding = trg.ne(pad)
        corrects = pred.eq(trg.data).masked_select(non_padding).sum().item()
        accuracy += corrects
        total += non_padding.sum().item()
        print(accuracy)
        
    test_error = total_loss / len(dataloaders['test'])
    test_accuracy = ( accuracy / total  ) * 100
    
    
    return test_error, test_accuracy

In [0]:
test_loss, test_accuracy = evaluate(model, fr_size, french_tokenizer, english_tokenizer)
print(test_loss)
print(test_accuracy)

848
1687
2508
3327
4126
4945
5784
6664
7477
8350
9178
10019
10822
11645
12490
13358
14179
14998
15870
16710
17579
18456
19284
20115
20956
21779
22610
23446
24297
25130
25952
26814
27617
28442
29318
30148
30951
31811
32642
33445
34297
35155
36004
36836
37645
38391
39242
40034
40838
41661
42514
43333
44183
45010
45821
46680
47561
48357
49160
49978
50805
51697
52550
53309
54139
55000
55837
56641
57485
58274
59092
59925
60773
61607
62432
63231
64055
64868
65705
66528
67372
68213
69039
69845
70662
71481
72265
73119
73970
74776
75608
76458
77250
78076
78880
79715
80567
81434
82212
83009
83787
84614
85425
86247
87086
87926
88771
89616
90458
91304
92184
93029
93809
94653
95496
96309
97129
97984
98818
99612
100412
101245
102021
102845
103700
104544
105380
106236
107094
107934
108767
109628
110438
111246
112059
112877
113715
114607
115469
116265
117057
117896
118687
119487
120308
121174
122007
122794
123589
124409
125230
126007
126827
127656
128484
129296
130131
130934
131777
132610
133405
13421

In [0]:

import torch
from torch.autograd import Variable


class Predictor(object):

    def __init__(self, model, src_vocab, tgt_vocab, src_vocab_rev, tgt_vocab_rev):
        """
        Predictor class to evaluate for a given model.
        Args:
            model (seq2seq.models): trained model. This can be loaded from a checkpoint
                using `seq2seq.util.checkpoint.load`
            src_vocab (seq2seq.dataset.vocabulary.Vocabulary): source sequence vocabulary
            tgt_vocab (seq2seq.dataset.vocabulary.Vocabulary): target sequence vocabulary
        """
        if torch.cuda.is_available():
            self.model = model.cuda()
        else:
            self.model = model.cpu()
        self.model.eval()
        self.src_vocab = src_vocab
        self.tgt_vocab = tgt_vocab
        self.src_vocab_rev = src_vocab_rev
        self.tgt_vocab_rev = tgt_vocab_rev

    def get_decoder_features(self, src_seq):
        src_id_seq = torch.LongTensor(src_seq)
        src_id_seq = src_id_seq.transpose(0, 1)
        
        trg = np.zeros((1, 23), dtype=int)
        trg = torch.LongTensor(trg)
        trg = trg.transpose(0, 1)
        
        if torch.cuda.is_available():
            src_id_seq = src_id_seq.cuda()
            trg = trg.cuda()

        with torch.no_grad():
          outputs, preds = self.model(src_id_seq, trg)

        return outputs, preds


    def predict(self, src_seq):
        """ Make prediction given `src_seq` as input.
        Args:
            src_seq (list): list of tokens in source language
        Returns:
            tgt_seq (list): list of tokens in target language as predicted
            by the pre-trained model
        """
        outputs, preds = self.get_decoder_features(src_seq)

        preds = preds.cpu().detach().numpy()
        #tgt_id_seq = preds.transpose(0, 1)
        tgt_id_seq = [preds[di].data[0] for di in range(1,23)]
        tgt_seq = [self.tgt_vocab_rev[tok] for tok in tgt_id_seq]
        
        return tgt_seq

    def predict_n(self, src_seq, n=1):
        """ Make 'n' predictions given `src_seq` as input.
        Args:
            src_seq (list): list of tokens in source language
            n (int): number of predicted seqs to return. If None,
                     it will return just one seq.
        Returns:
            tgt_seq (list): list of tokens in target language as predicted
                            by the pre-trained model
        """
        other = self.get_decoder_features(src_seq)

        result = []
        for x in range(0, int(n)):
            length = other['topk_length'][0][x]
            tgt_id_seq = [other['topk_sequence'][di][0, x, 0].data[0] for di in range(length)]
            tgt_seq = [self.tgt_vocab.itos[tok] for tok in tgt_id_seq]
            result.append(tgt_seq)

        return result

In [0]:
predictor = Predictor(model, english_tokenizer, french_tokenizer, english_tokenizer_rev, french_tokenizer_rev)


seq_str = "he saw a old yellow truck ."
seq_str = delimit_sentence(seq_str)
seq_str 


'<sos> he saw a old yellow truck . <eos>'

In [0]:
#seq = seq_str.strip().split()
seq = []
for word in seq_str.split():
    if word not in punctuation:
       seq.append(word)

  
seq = [english_tokenizer[tok] for tok in seq]
seq

[2, 28, 130, 102, 113, 114, 103, 3]

In [0]:
feature = np.zeros((1, 23), dtype=int)
trunc = seq[:23]
feature[:, :len(trunc)] = trunc
feature 

array([[  2,  28, 130, 102, 113, 114, 103,   3,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [0]:
src_id_seq = torch.LongTensor([feature]).view(1, -1)
src_id_seq = src_id_seq.transpose(0, 1)

In [0]:
src_id_seq

tensor([[  2],
        [ 28],
        [130],
        [102],
        [113],
        [114],
        [103],
        [  3],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0],
        [  0]])

In [0]:
src_id_seq = src_id_seq.cuda()

In [0]:
trg = np.zeros((1, 23), dtype=int)
trg = torch.LongTensor(trg)
trg = trg.transpose(0, 1)
trg = trg.cuda()

In [0]:
with torch.no_grad():
     outputs, preds = model(src_id_seq, trg)

In [0]:
preds

tensor([[  0.],
        [  5.],
        [119.],
        [151.],
        [146.],
        [186.],
        [111.],
        [135.],
        [  3.],
        [  3.],
        [  3.],
        [  3.],
        [  3.],
        [  3.],
        [  3.],
        [  3.],
        [111.],
        [  3.],
        [  3.],
        [  3.],
        [  3.],
        [  3.],
        [  3.]], device='cuda:0')

In [0]:
preds = preds.cpu().detach().numpy()

In [0]:
preds

array([[  0.],
       [  5.],
       [119.],
       [151.],
       [146.],
       [186.],
       [111.],
       [135.],
       [  3.],
       [  3.],
       [  3.],
       [  3.],
       [  3.],
       [  3.],
       [  3.],
       [  3.],
       [111.],
       [  3.],
       [  3.],
       [  3.],
       [  3.],
       [  3.],
       [  3.]], dtype=float32)

In [0]:
xxx, yyy = predictor.get_decoder_features(feature)

In [0]:
yyy

tensor([[  0.],
        [  5.],
        [119.],
        [151.],
        [146.],
        [146.],
        [186.],
        [  3.],
        [  3.],
        [  3.],
        [  3.],
        [  3.],
        [  3.],
        [  3.],
        [  3.],
        [  3.],
        [  3.],
        [  3.],
        [  3.],
        [  3.],
        [  3.],
        [  3.],
        [  3.]], device='cuda:0')

In [0]:
preds = yyy.cpu().detach().numpy()

In [0]:

tgt_id_seq = [preds[di].data[0] for di in range(1,23)]
tgt_id_seq

[5.0,
 119.0,
 151.0,
 146.0,
 146.0,
 186.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0,
 3.0]

In [0]:
output = predictor.predict(feature)

In [0]:
tgt_seq_output = ' '.join([word for word in output])

In [0]:
tgt_seq_output

'il a vu un vieux camion jaune <eos> <eos> <eos> <eos> <eos> <eos> <eos> <eos> <eos> <eos> <eos> <eos> <eos> <eos> <eos>'

In [0]:
print(predictor.predict(feature))

['il', 'a', 'vu', 'un', 'vieux', 'camion', 'jaune', '<eos>', '<eos>', '<eos>', '<eos>', '<eos>', '<eos>', '<eos>', '<eos>', '<eos>', '<eos>', '<eos>', '<eos>', '<eos>', '<eos>', '<eos>']


In [0]:
seq_str = "new jersey is sometimes quiet during autumn , and it is snowy in april ."
seq_str = delimit_sentence(seq_str)
seq_str 

'<sos> new jersey is sometimes quiet during autumn , and it is snowy in april . <eos>'

In [0]:
seq = []
for word in seq_str.split():
    if word not in punctuation:
       seq.append(word)

  
seq = [english_tokenizer[tok] for tok in seq]
seq

[2, 19, 25, 1, 10, 69, 6, 41, 9, 5, 1, 57, 4, 46, 3]

In [0]:
feature = np.zeros((1, 23), dtype=int)
trunc = seq[:23]
feature[:, :len(trunc)] = trunc
feature 

array([[ 2, 19, 25,  1, 10, 69,  6, 41,  9,  5,  1, 57,  4, 46,  3,  0,
         0,  0,  0,  0,  0,  0,  0]])

In [0]:
xxx, yyy = predictor.get_decoder_features(feature)

In [0]:
preds = yyy.cpu().detach().numpy()

In [0]:
tgt_id_seq = [preds[di].data[0] for di in range(1,23)]
tgt_id_seq

[36.0,
 35.0,
 1.0,
 10.0,
 68.0,
 38.0,
 13.0,
 26.0,
 8.0,
 5.0,
 113.0,
 4.0,
 50.0,
 3.0,
 50.0,
 3.0,
 4.0,
 3.0,
 3.0,
 50.0,
 3.0,
 4.0]

In [0]:
output = predictor.predict(feature)

In [0]:
tgt_seq_output = ' '.join([word for word in output])
tgt_seq_output

"new jersey est parfois calme pendant l' automne et il est neigeux en juillet <eos> juillet juillet juillet juillet <eos> juillet <eos>"